<a href="https://colab.research.google.com/github/sumalatha456/MINI_NLP-PROJECTS/blob/main/ML_MODEL_USING_FLASK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ML MODEL BUILDING AND DEPLOYMENT USING FLASK

##Fake News Detection

In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt




In [6]:
import pandas as pd

# Try using a different delimiter, such as a tab or semicolon
df = pd.read_csv("fake_news.csv", encoding='ISO-8859-1', sep=',', on_bad_lines='skip')

print(df.head())

  id                                              title              author  \
0  0  House Dem Aide: We Didnt Even See Comeys Let...       Darrell Lucus   
1  1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2  2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3  3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4  4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text label  
0  House Dem Aide: We Didnt Even See Comeys Let...     1  
1  Ever get the feeling your life circles the rou...     0  
2  Why the Truth Might Get You Fired October 29, ...     1  
3  Videos 15 Civilians Killed In Single US Airstr...     1  
4  Print \nAn Iranian woman has been sentenced to...     1  


In [7]:
df.shape

(22568, 5)

In [8]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22568 entries, 0 to 22567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      22568 non-null  object
 1   title   21146 non-null  object
 2   author  19252 non-null  object
 3   text    20762 non-null  object
 4   label   20531 non-null  object
dtypes: object(5)
memory usage: 881.7+ KB


In [9]:
df.isna().sum()

id           0
title     1422
author    3316
text      1806
label     2037
dtype: int64

In [10]:
df = df.drop(['id'], axis =1)

In [11]:
df = df.dropna()

In [12]:
df = df.fillna("")

In [13]:
df=df.drop(['title','author','text'],axis=1)

In [14]:
df.head()

label
0     1
1     0
2     1
3     1
4     1

In [32]:

# Install the package
!pip install textblob

# Example usage
from textblob import TextBlob

text = "I love programming with Python!"
blob = TextBlob(text)


In [33]:
import pandas as pd

# Try using a different delimiter, such as a tab or semicolon
df = pd.read_csv("fake_news.csv", encoding='ISO-8859-1', sep=',', on_bad_lines='skip')

# Print the columns of the DataFrame to confirm if 'content' exists
print(df.columns)

# Check if 'content' is in the columns
if 'content' in df.columns:
    df['content'] = df['content'].apply(lambda x: "".join(x.lower() for x in x.split()))
else:
    print("Column 'content' not found in the DataFrame.")

Index(['id', 'title', 'author', 'text', 'label'], dtype='object')
Column 'content' not found in the DataFrame.


In [34]:
df=df.drop(['title','author','text'],axis=1)

In [35]:
print(df.columns)  # To check if 'Content' is among the columns
print(df.head())   # To see a preview of the DataFrame


Index(['id', 'label'], dtype='object')
  id label
0  0     1
1  1     0
2  2     1
3  3     1
4  4     1


In [36]:
if 'Content' in df.columns:
    value = df['Content']
else:
    print("Key 'Content' not found in DataFrame")



Key 'Content' not found in DataFrame


In [38]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'content': ['Hello World!', 'Pandas is great', None, 'Python Programming']
})

# Corrected code
df['content'] = df['content'].apply(lambda x: "".join(x.lower() for x in x.split()) if pd.notnull(x) else "")

print(df)


             content
0        helloworld!
1      pandasisgreat
2                   
3  pythonprogramming


In [39]:
df['content'] = df['content'].apply(lambda x: "".join(x.lower() for x in x.split()))

In [40]:
#REmoving punctuations
df['content']= df['content'].str.replace('[^\w\s]','')

In [41]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [42]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
df['content']= df['content'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

In [57]:
import pandas as pd

# Sample DataFrame for demonstration
df = pd.DataFrame({
    'author': ['Alice', 'Bob', 'Charlie'],
    'content': ['Post 1', 'Post 2', 'Post 3']
})

# Check if 'author' column exists
if 'author' in df.columns:
    print("Column 'author' exists in the DataFrame")
else:
    print("Column 'author' does not exist in the DataFrame")


Column 'author' exists in the DataFrame


In [52]:
# Assuming you want to recreate 'content' from the original CSV
import pandas as pd

# Re-read the original CSV to get the 'author', 'title', and 'text' columns
df_original = pd.read_csv("fake_news.csv", encoding='ISO-8859-1', sep=',', on_bad_lines='skip')


In [55]:
if 'author' in df.columns:
    df['author'] = df['author'].apply(lambda x: x.lower() if pd.notnull(x) else "")
else:
    print("Column 'author' not found in DataFrame")


Column 'author' not found in DataFrame


In [56]:
if 'author' in df.columns:
    df['author'] = df['author'].fillna('Unknown')  # Replace NaN with 'Unknown'
    print(df['author'])
else:
    print("Column 'author' not found in the DataFrame")


Column 'author' not found in the DataFrame


In [62]:
# Assuming you want to recreate 'content' from the original CSV
import pandas as pd

# Re-read the original CSV to get the 'author', 'title', and 'text' columns
df = pd.read_csv("fake_news.csv", encoding='ISO-8859-1', sep=',', on_bad_lines='skip')

# Now you can access 'author', 'title', and 'text' columns
df['content'] = df['author'].fillna('') + '' + df['title'].fillna('') + '' + df['text'].fillna('')

In [63]:
!pip install textblob
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
from textblob import Word
df['content']= df['content'].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))
df['content'].head()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


0    Darrell LucusHouse Dem Aide: We Didnt Even Se...
1    Daniel J. FlynnFLYNN: Hillary Clinton, Big Wom...
2    Consortiumnews.comWhy the Truth Might Get You ...
3    Jessica Purkiss15 Civilians Killed In Single U...
4    Howard PortnoyIranian woman jailed for fiction...
Name: content, dtype: object

In [64]:
X = df[['content']]
y = df['label']

In [74]:
df = df.dropna()
df = df.fillna("")

In [75]:
df_filled = df.fillna(0)
df_dropped = df.dropna()

In [78]:
from sklearn.model_selection import train_test_split

# Check for classes with only one sample
unique_classes, class_counts = np.unique(y, return_counts=True)
classes_with_one_sample = unique_classes[class_counts == 1]

# If there are classes with only one sample, remove them or handle them differently
if len(classes_with_one_sample) > 0:
    print("Classes with only one sample:", classes_with_one_sample)
    # Option 1: Remove rows corresponding to these classes
    df = df[~df['label'].isin(classes_with_one_sample)]
    X = df[['content']]
    y = df['label']
    # Option 2: Handle them in a way specific to your dataset and task
    # (e.g., oversampling, data augmentation, etc.)
    # ...

# Now you can proceed with train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=45, stratify=y)

# Checking the shapes of the resulting datasets
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

Classes with only one sample: [' \x11 \x18\x1a! 2 >G5@54=>9 @07 ?@>45<>=AB@8@>20;8 A2>N ?>@078B5;L=CN A?>A>1=>ABL ?@52@0B8BL A;>6=K9 ?5@8>4 2 C4>1=K9 (A B>G:8 7@5=8O AB@0B538G5A:8E ?5@A?5:B82) <><5=B 4;O C:@5?;5=8O A2O759 <564C AB@0=0<8-G;5=0<8 3@C??K.'
 ' \x12;048<8@ \x12;048<8@>28G.' ' \x14 A:070; "@0<?. '
 ' \x14 A>60;55B \x1fCB8=. \x1e :0:8E A8;0E 845B @5GL? '
 ' \x1f5B@>< 8 4@C38<8.'
 ' $49 billion); total spending for the false war-on-drugs at about $75 billion. '
 ' - 3>2>@8BAO 2 A>>1I5=88 !# !\x1a ?>  5A?C1;8:5 \x1c>@4>28O. '
 ' 2 :0:CN AB>@>=C ;CGH5 A?0BL 3>;>2>9. \x15ABL :0:85-B> @5:><5=40F88? '
 ' 2 B>< G8A;5 A 55  538>=0;L=K< F5=B@>< ?> ?@525=B82=>9 48?;><0B88 4;O &5=B@0;L=>9 \x10788.'
 " 2016 Wasn't it just last week that he said a president can't whine and blame others? #BiggestWhinerAndBlamerEver https://t.co/ZIQIel4aeP "
 ' 2=>AOB @50;L-=K9 2:;04 2 8E >ACI5AB2;5=85.'
 ' 2E>4OI59 2 ?5@5G5=L <564C=0@>4=KE B5@@>@8AB8G5A:8E >@30=870F89.'
 ' 2K720; 1>;LH>9 >1I5AB25==K9 @57>=

In [79]:
from sklearn.model_selection import train_test_split

# Splitting the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=45, stratify=y)

# Checking the shapes of the resulting datasets
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)


X_train shape: (12558, 1)
X_test shape: (5383, 1)
y_train shape: (12558,)
y_test shape: (5383,)


In [80]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(12558, 1)
(5383, 1)
(12558,)
(5383,)


In [82]:
print(X_train.shape)

(12558, 1)


In [85]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn import metrics

# Create a TfidfVectorizer object
vectorizer = TfidfVectorizer()

# Fit the vectorizer to the training data and transform it
X_train_tfdif = vectorizer.fit_transform(X_train['content'])

# Transform the test data using the fitted vectorizer
X_test_tfdif = vectorizer.transform(X_test['content'])

# Now you can proceed with fitting the classifier
pclf = PassiveAggressiveClassifier()
pclf.fit(X_train_tfdif, y_train)
predictions = pclf.predict(X_test_tfdif)
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

       2016        0.00      0.00      0.00         1
           0       0.97      0.97      0.97      3044
           1       0.96      0.96      0.96      2338

    accuracy                           0.97      5383
   macro avg       0.64      0.64      0.64      5383
weighted avg       0.97      0.97      0.97      5383



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [87]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [89]:
tfdif_vec = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', max_features=5000)  # Changed 'token_patterns' to 'token_pattern'
tfdif_vec.fit(X_train['content'])  # Changed 'tfdif_vect' to 'tfdif_vec'
X_train_tfdif = tfdif_vec.transform(X_train['content'])  # Changed 'tfdif_vect' to 'tfdif_vec'
X_test_tfdif = tfdif_vec.transform(X_test['content'])  # Changed 'tfdif_vect' to 'tfdif_vec'

In [90]:
print(metrics.confusion_matrix(y_test,predictions))

[[   0    0    1]
 [   0 2952   92]
 [   0   94 2244]]


In [91]:
from sklearn.neural_network import MLPClassifier
mlpclf = MLPClassifier(hidden_layer_sizes=(256,64,16),activation = 'relu', solver = 'adam')
mlpclf.fit(X_train_tfdif, y_train)
predictions = mlpclf.predict(X_test_tfdif)
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

       2016        0.00      0.00      0.00         1
           0       0.96      0.97      0.96      3044
           1       0.96      0.94      0.95      2338

    accuracy                           0.96      5383
   macro avg       0.64      0.64      0.64      5383
weighted avg       0.96      0.96      0.96      5383



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [92]:
print(metrics.confusion_matrix(y_test,predictions))

[[   0    0    1]
 [   0 2943  101]
 [   0  132 2206]]


In [93]:
import pickle
#save trained model to file
pickle.dump(mlpclf,open('fakenews1.pkl','wb'))

In [96]:
#load the model from the disk
loaded_model = pickle.load(open('fakenews1.pkl','rb'))

X_test_tfdif = tfdif_vec.transform(X_test['content'])

# Now calculate the score using the transformed data
result = loaded_model.score(X_test_tfdif, y_test.values)
print(result)

0.9565298160876834
